
<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var Magento\Framework\Escaper $escaper */
/** @var $phoneNumberViewModel Juno\Theme\ViewModel\PhoneNumber */
$phoneNumberViewModel = $block->getData('phone_number_view_model');
?>

<div class="phone-number">
    614-218-1551
    <?= $block->getBaseUrl() ?>
    <?= $escaper->escapeHtml($phoneNumberViewModel->getPhoneNumber()) ?>
</div>